//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Date : 23-06-2015
//
// </auto-generated>
//------------------------------------------------------------------------------
namespace NHibernateTest.Mapping
{
    using System;
    using System.Text;
    using System.Collections.Generic;
    using System.Linq;
    using FluentNHibernate.Mapping;
    using NHibernateTest.Models;

    /// <summary>
    /// Mapping table T_GROUP
    /// </summary>
    /// <remarks>
    /// Questa classe genera il proxy per mappare la tabella T_GROUP
    /// </remarks>
    public class GroupMap : ClassMap<Group>
    {
        /// <summary>
        /// Inizializza una nuova istanza
        /// </summary>
        public GroupMap()
        {
            Table("T_GROUP");
            LazyLoad();
            Id(x => x.CdGroup).GeneratedBy.Identity().Column("CD_GROUP");
            Map(x => x.CaGroup).Column("CA_GROUP").Not.Nullable();
            Map(x => x.FlDelete).Column("FL_DELETE").Not.Nullable();
        }
    }
}
